-- 코드를 입력하세요
SELECT INFO.FLAVOR
FROM 
    FIRST_HALF AS HALF INNER JOIN ICECREAM_INFO AS INFO
    ON HALF.FLAVOR = INFO.FLAVOR
WHERE
    HALF.TOTAL_ORDER > 3000 AND INFO.INGREDIENT_TYPE = 'fruit_based';