-- 코드를 입력하세요
# SELECT 
#     BOARD.TITLE, BOARD.BOARD_ID, 
#     REPLY.REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, REPLY.CREATED_DATE
# FROM 
#     USED_GOODS_BOARD AS BOARD, 
#     USED_GOODS_REPLY AS REPLY
# WHERE 
#     BOARD.BOARD_ID = REPLY.BOARD_ID
#     AND BOARD.CREATED_DATE BETWEEN 2022-10-01 AND 2022-10-31
# ORDER BY REPLY.CREATED_DATE, BOARD.TITLE;

-- 2트
# SELECT 
#     BOARD.TITLE, BOARD.BOARD_ID, 
#     REPLY.REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, REPLY.CREATED_DATE
# FROM 
#     USED_GOODS_BOARD AS BOARD INNER JOIN USED_GOODS_REPLY AS REPLY
#     ON BOARD.BOARD_ID = REPLY.BOARD_ID
# WHERE 
#     BOARD.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
# ORDER BY REPLY.CREATED_DATE, BOARD.TITLE;

-- 3트
SELECT 
    BOARD.TITLE, BOARD.BOARD_ID, 
    REPLY.REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, SUBSTR(REPLY.CREATED_DATE, 1, 10) AS CREATED_DATE
FROM 
    USED_GOODS_BOARD AS BOARD INNER JOIN USED_GOODS_REPLY AS REPLY
    ON BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE 
    BOARD.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY REPLY.CREATED_DATE, BOARD.TITLE;